version: '3.4'
services:

  achat-image:
    build: .
    ports:
      - 8089:8089
    image: achat-image
    environment:
      - spring.datasource.url=jdbc:mysql://db-mysql:3306/achat?createDatabaseIfNotExists=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - db-mysql

  db-mysql:
    image: mysql:5.7
    container_name: mysql_new
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achat
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
